title: builderscon::blog
description: > 
  builderscon is a festival for the technology lovers.
url: http://blog.builderscon.io
mainurl: http://builderscon.io
twitter_username: builderscon
github_username:  builderscon
fb_app_id: 1537973726511652
fb_page_id: 1233910219973110
markdown: kramdown
permalink: /:year/:month/:day/:title.html

authors:
  lestrrat:
    display_name: Daisuke Maki
    twitter: lestrrat 
    github: lestrrat
    web: http://lestrrat.github.io
    gravatar_id: f34e1745f7f8286586e921f7830eca78
  richard-imaoka:
    display_name: richard
    twitter: RichardImaokaJP
    github: richard-imaoka
    web: http://richard-imaoka.github.io
    gravatar_id: 14bfbc98a7d5ed3574be08f6b176ce70
  kamadango:
    display_name: kamadango
    twitter: kamadango
    github: kamadango
    gravatar_id: 5510e0724bae0bcb8266b4ff854c9e79
  hasegawatomoki:
    display_name: Tomoki Hasegawa
    twitter: tomzoh
    github: hasegawa-tomoki
    gravatar_id: e181a7f0a9cdd4d975e84feb37fc64f7

