title: builderscon blog
description: > 
  builderscon is a festival for the technology lovers.
url: "http://blog.builderscon.io"
twitter_username: builderscon
github_username:  builderscon

markdown: kramdown